export const data = [
  {
    id: 1,
    name: "TOZO T6 True Wireless Earbuds Bluetooth Headphon...",
    price: 70,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    hot: true,
    star: 5,
    comment: 753,
  },
  {
    id: 2,
    name: "Samsung Electronics Samsung Galexy S21 5G",
    price: 2300,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    star: 5,
    comment: 536,
  },
  {
    id: 3,
    name: "Amazon Basics High-Speed HDMI Cable (18 Gbps, 4K/6",
    price: 360,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    best_seller: true,
    star: 5,
    comment: 423,
  },
  {
    id: 4,
    name: "Portable Wshing Machine, 11lbs capacity Model 18NMF",
    price: 80,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    star: 4,
    comment: 816,
  },
  {
    id: 5,
    name: "Wired Over-Ear Gaming Headphones with USB",
    price: 1500,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    star: 5,
    comment: 647,
  },
  {
    id: 6,
    name: "Polaroid 57-Inch Photo/Video Tripod with Deluxe Tripod Ca",
    price: 1600,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    off: 25,
    star: 4,
    comment: 877,
  },
  {
    id: 7,
    name: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
    price: 250,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    star: 5,
    comment: 426,
  },
  {
    id: 8,
    name: "4K UHD LED Smart TV with Chromecast Built-in",
    price: 220,
    sale: true,
    image: "https://m.media-amazon.com/images/I/51Nnp56PlbL.jpg",
    star: 5,
    comment: 583,
  },
];
